#pragma once
#include "languageScene.h"
#include<string>
class TargetText
{
public:
	static char language;
	std::string koreanText[50] = {
		"삶이 있는 한 희망은 있다.",
		"산다는것 그것은 치열한 전투이다.",
		"피할수 없으면 즐겨라.", 
		"내일은 내일의 태양이 뜬다.",
		"절대 어제를 후회하지 마라.",
		"행복은 습관이다.",
		"일에 광적으로 집중하는 것이다.",
		"고통을 즐길 줄 알아야 해.",
		"직업에서 행복을 찾아라.", 
		"당신은 계단을 이용해야만 합니다.",
		"엘리베이터는 고장입니다.",
		"겨울이 오면 봄이 멀지 않으리.",
		"여름은 더워.", 
		"겨울은 추워.",
		"봄이 좋아.",
		"가을이 좋아.",
		"고개 숙이지 마십시오.",
		"돈이란 바닷물과도 같다.", 
		"마시면 마실수록 목이 말라진다.",
		"화가 날 때는 100까지 세라.",
		"그것이 나의 길이다.",
		"평생 살 것처럼 꿈을 꾸어라.",
		"내일 죽을 것처럼 오늘을 살아라.",
		"네 믿음은 네 생각이 된다.",
		"그대 자신의 영혼을 탐구하라.",
		"명언과 아무말이 섞여있습니다.",
		"명언도 몇개는 일부분입니다.",
		"이 길은 그대만의 길이요.",
		"그대 혼자 가야할 길임을 명심하라.",
		"고통이 남기고 간 뒤를 보라.",
		"고난이 지나면 반드시 기쁨이 스며든다.",
		"화려한 일을 추구하지 말라.",
		"반드시 실천하여야 한다.",
		"마음만을 가지고 있어서는 안된다.",
		"배울 것이 많은 법이다.",
		"내 비장의 무기는 아직 손안에 있다.",
		"인생을 즐기자.",
		"일하여 얻으라.",
		"내일은 스스로 만드는 것이다.",
		"먹고싶은 것을 먹는데 무슨 재미가 있겠나.",
		"최저에서 시작하라.",
		"그러면 재능이 드러날 것이다.",
		"더 많은 실수를 저지르리라.",
		"길을 알게 된다는 것이다.",
		"삶을 사는 데는 단 두가지 방법이 있다.",
		"늦은 때라곤 없다.",
		"한 번 실패와 영원한 실패를 혼동하지 마라.",
		"최악일 때는 욕설을 퍼부어라.",
		"인생의 참다운 맛을 모른다.",
		"진짜 문제는 사람들의 마음이다."
	};
	std::string englishText[50] = {
		"I agree.",
		"I am deeply touched.",
		"I am a little disappointed.",
		"I am all set.",
		"I am aware of that.",
		"I am nearsighted.",
		"I am serious.",
		"I have a long way to go.",
		"I have no energy.",
		"It is muggy.",
		"Just kidding.",
		"Keep out of my way.",
		"Keep the change.",
		"Keep it confidential.",
		"Keep it to yourself.",
		"Keep in touch.",
		"Let's eat out.",
		"Let's see.",
		"Let it be!",
		"Large or small?",
		"Knock it off.",
		"Keep your chin up!",
		"Make yourself at home.",
		"Never say die.",
		"Next time.",
		"Never better.",
		"Most likely.",
		"It’s not fair.",
		"It takes time.",
		"It is windy.",
		"It makes sense.",
		"It's really bad.",
		"It's my turn.",
		"It's all your fault.",
		"It's freezing.",
		"It's free.",
		"It's beautiful.",
		"Look who's here.",
		"May I interrupt you?",
		"Maybe some other time.",
		"Me, too.",
		"Maybe not.",
		"Not really.",
		"Out of the question.",
		"On the contrary.",
		"Occupied.",
		"Now what?",
		"Nothing new.",
		"Nothing much.",
		"Not too good."
	};
	TargetText();
	~TargetText();

	void setLanguage(char l);
	std::string getText();
};

